### PR TITLE
Feature/builder

### PR DESCRIPTION
**Pull request by theiskaa**
Resolves: #26 
---
Require to take `suggestionList`, `textController`, and `itemBuilder`.

```dart
class BuilderExample extends StatelessWidget {
  final textEditingController = TextEditingController();
  List<String> suggestionsList = ['test@gmail.com', 'test1@gmail.com'];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: FieldSuggestion.builder(
        hint: 'Email',
        textController: textEditingController,
        suggestionList: suggestionsList,
        itemBuilder: (BuildContext context, int index) {
          return GestureDetector(
            onTap: () => textEditingController.text = suggestionsList[index],
            child: Card(
              child: ListTile(
                title: Text(suggestionsList[index]),
                leading: Container(
                  height: 30,
                  width: 30,
                  decoration: BoxDecoration(
                    color: Colors.blueGrey,
                    shape: BoxShape.circle,
                  ),
                  child: Center(
                    child: Text(suggestionsList[index][0].toUpperCase()),
                  ),
                ),
              ),
            ),
          );
        },
      ),
    );
  }
}
```

### CODE REVIEW

**Comment by g-scosta** [comment]
Hey @theiskaa, correct me if I'm wrong but I think this index that are exposed in the builder refers to the index of matchers. So if we have a list of 10 items and find 2 matchs the index will be 0 and 1.

Before passing the index to the exposed builder we could do suggestionsList.indexOf(matchers[index]].

**Comment by theiskaa** [comment]
Okay, I should understand what you mean exactly, I'll do it soon.

**Comment by theiskaa** [comment]
@g-scosta Hi man, I can't figure out what you exactly mean, can you tell me more about it?

**Comment by g-scosta** [comment]
The index that you are passing to the itemBuilder is the index coming from the itemBuilder inside `ListView.separated` that receives the `matchers.length` as a argument. So this item builder will always have the index from 0 to the length of the matchers. 

Inside `suggestionListItem(index)` you use the index in `matchers[index]` but we don't have access to matchers outside FieldSuggestion. 

So if we have a list of 10 items and the last three is in the matchers, the index will be 0-2 and not 7-9. If we do suggestionsList[index] in the itemBuilder  we will get the first three values, not the last.

**Comment by theiskaa** [comment]
@g-scosta Understood, Okay I'll think about that problem, thanks for reporting.

**Comment by theiskaa** [comment]
@g-scosta Hey bro, I solved that problem so now it works properly :D, Just need tests for it. 
And if you have time, you can check it and make the simple review, tonight I'll write tests also, and then we can merge PR

**Comment by theiskaa** [comment]
Yeah, everything is fine now, @g-scosta you can make a review/test and if you are done, then we can merge the PR and close the issue.

**Comment by g-scosta** [comment]
Hey @theiskaa I tested and now it's working, but I noticed a great perfomance issue, I have 500+- items to be filtered and the fps dropped a lot. This is probably due to transforming the list of objects into a list of maps everytime inside itemBuilder.

I did some adjustments and tested and with these fixes it's working fast. I'll post these adjustments here:

Instead of transforming the list inside itemBuilder I've created a variable `List<dynamic> suggestionListJson = <dynamic>[]; `  inside `_FieldSuggestionState` and after initState I did the transformation 

```
super.initState();
    suggestionListJson =
        widget.suggestionList.map((e) => e.toJson().toString()).toList();
    // Add listener to textController, for listen field and create matchers list.
    widget.textController.addListener(_textListener);
```

So the part that you assign the indexes variable became 

```
// We need indexes to determine right index of concrete item.
                    var indexes = matchers.map((e) {
                      // If suggestion list isn't Object list then just return index of "e".
                      if (!isObjList(widget.suggestionList))
                        return widget.suggestionList.indexOf(e);

                      return suggestionListJson.indexOf(e.toString());
                    }).toList();
```

I also noticed that return the ListView it's unecessary, it can return the itemBuilder like that

`return widget.itemBuilder!(context, indexes[i]);`

I'm testing with these fixes and it's on normal perfomance. I think changing that would be enough to release.

**Comment by theiskaa** [comment]
Really perfect detections, thanks again 😄Okay, I'll add them.

**Comment by theiskaa** [comment]
@g-scosta Done! Everything applied/added what you mentioned above. Just check it and if you're ok then we can merge the PR.

**Comment by g-scosta** [comment]
Great! I think it's ready for merge

**Comment by theiskaa** [comment]
Ok, Thank you again for your time and request and for the great idea!

**Pull request merged**
